name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        IMAGE_ID=docker.io/luiscoco/webapidotnet8

        # Build the Docker image
        docker build . --file Dockerfile --tag $IMAGE_ID:latest

        # Push the image to Docker Hub
        docker push $IMAGE_ID:latest
